dist: trusty
sudo: required
language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0
addons:
  postgresql: '9.5'
env:
  global:
    - PGPORT=5432
    - MIX_ENV=test VERBOSE_TEST=true

before_script:
  - nvm install 8.9.0

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

before_deploy:
  - cd ./assets
  - yarn install
  - ./node_modules/.bin/brunch build -p
  - cd ..
  - MIX_ENV=prod mix phx.digest
  - MIX_ENV=prod mix release --env=prod

branches:
  only:
    - master
    - /^v[\d.]+/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LLvtkR7ckBtQYXm7UMsI8BuLdRLJFSg5iLhs/q6GaWvFPJfbXpKaMsO4NB9ClFFTvCOQYvpyFQP4c3oMkfphvm9/94eBp8w/C7sf8uakHyeq1bLWjSuxnpgfOht8BAWJQ+7O0tZ65MkbJ5UuLC4Hzi8pvLR2BQN/8F9BhQhW3P8Q0Uz/ygIoPwHPLV0/oco2o2NlQgcRLk7Yy3W1dZZy3/5po1JqE7v2z9hQDZPWgTi2sR3LkYyIfc07J2qAfAoLlT3/pjUtmWtyeJk1gsnzeq86uyQdBmcrr30ZIs92aroeZRp3ltVHBzEzqFV70D+Z4W9kFirancqF4rJxQt++ZTcEUQdEtUm0uvxYgw3XKMxpqIxhDuZDbfpZ9Ox8nTZ1Ain0JRGX2iMcEEWxm/cLon2SIox8cBqtgkB3syyfwnZHSkTtZtOA6aqSz9rrBJZ6MvjMwwFyRtYLTa829XB6SI8SkTS8EbXufyEXX9I0o2ttYRYgP0qYvJ0WH/GPtaNJERqWcPEw6oBf4oKCau2cQ0JcNFVkh+TIIN2ds0UdQIEOo1RsdfrYqEX14dZYvUCgW3Birwvh43Gp4to3/gulEcgb+NUvuXLr7YsbExiOw0j4RL35BCppWvtWn7N2Y+KwzTTvToU6zemM77tXKcM6swdwcfi7t8x0IBSxkdsZyxg=
  file_glob: true
  file: _build/prod/rel/mcd/releases/*/*.tar.gz
  on:
    tags: true
