dist: trusty
sudo: required
language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0
addons:
  postgresql: '9.5'
env:
  global:
    - PGPORT=5432
    - MIX_ENV=test VERBOSE_TEST=true
    - secure: ZM+kmaVZ0KJ0e1joimG5tvXJI8bNN4nZpJ1dLhJS51JD/y6fDLXexpeJvY2zkt7Sr8p2hr1g8d57ALHmIfmlDqtbKi4b8eLttTwBz/Q6PdKvuBnUANAYJJUzxrxGqtnwsyAtFgB44hsDdiMcsZ9sB7eIZt1XH2QSBDWbINaq4NwTqj2Pp3pnFsNflez2UzsEetGb8DwQQ87L3jHIkPEag8y26MeaSufxav/wVTkdhyBXhLZSMwECg6quurPch7BHTHxLVEy6fQk47IXEaGuzQLQz13HM1Pu0b/t4IhmyWbzYoORDCfIA337Li3Tmma95EL0AbZIBGEUygD/fULAJHNosG0hAbpSWufT40RdcQzsWe5aSylhVOKVMTFQRxtDsw6znKqG6rooiQLOMaekNT15osKjyIfHIZDZaIu+KrYClPXxNEm/CW01S30cSmHF5/YKzTy+6frfUUobpZTWDp1017Sz1PDDrTgiBqCTK1+ESUZeXcRgConpfX3SKQDHBBKKBu8HLznpM+vike0Yw/PqUVRwd3M+bwkqVy8aU7hYAoqSPNp/aMBdXpQNTl+dRhCmSgw+OVpUsqFe6e/vqrbzaCUZ5DOxrC++iTrGJTqgicg6VwcW9EvwCr/maKJtp02lVxaBw22DYtfW0pYyQPrAx+VsBzPcs3R+lPugZlpQ=

before_script:
  - nvm install 8.9.0

script:
  - mix format --check-formatted
  - mix compile --warnings-as-errors
  - mix coveralls
  - mix credo

before_deploy:
  - cd ./assets
  - yarn install
  - ./node_modules/.bin/brunch build -p
  - cd ..
  - MIX_ENV=prod mix phx.digest
  - MIX_ENV=prod mix release --env=prod

after_deploy:
  - curl
    -X POST
    -H 'Content-type:application/json'
    -d "{\"text\":\"tar.gz built for $TRAVIS_REPO_SLUG - tag $TRAVIS_TAG\"}" $SLACK_HOOK

branches:
  only:
    - master
    - /^v[\d.]+/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
     secure: KHGKV9JhdUxlTpkD734Jr6TUDBp50dTAHvbmOnQaLc8aoDNzNbh7nuIVuUpJp+ozP0y19X0NHUHIGPCX7IEmzSWRtAxgMrKnUEp75wjdTw6pMBPkzXrWTyKJFuC3yQAm29DMqPa8kyYx+g+idPGA61v6NLiHf3WKcJmVyEo8g+Al9KuAcgUtPRsS/wf+wSP+RQ8ARrrq7Na2M9SvskXcxQOYSjTvyCj/V+kIlsRu6OzA4Bl+lx36stQkh9nrLQoOfZECj5U/JtJjL4mD2yd41DLVwkuj2ts3+5tm/YLTfIMWt/tsoSUtZY2wshjDT5grKeG8xIOqYIOHukf+3ZDZz5mXdNdMYnZAY8EdKh4RHrt2dhIIQKW2TgYtm66qVwYAftcK/ab9NwQS6MlS5JliBgSvHc3WQBEIaWmwYxGg097G4F3Vieq4yvoVC/6tuU7ovR7COzh4aPuXijUUvIj6+oxF8gLZPWTMUTGR7Q1gCYBTVtvk/NJp1lr2nuIglxR+VBLlknUazeunMhVU7V4FO7mBYmezHM/Y7MYO7rF7jX1pR5lmBe7o5yR8Waya3M9+iYlukLnyVmue2PKDdRVKbH8l8HILn1wqHzTwelIV5oFHlNLsSxZIzKrOdePlPEPOkXR8KPIEr1TpS2Lede+oB/c0D/JNhxSgJhvlwl+ITSY=
  file_glob: true
  file: _build/prod/rel/mcd/releases/*/*.tar.gz
  on:
    tags: true
